# apt tasks file for ansible-role-chrome
# via http://linuxg.net/how-to-install-google-chrome-42-stable-on-the-most-popular-linux-systems-via-the-official-google-repository/

- name: "apt | ensure Google linux signing key present"
  apt_key: 
    url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
    state: "present"

- name: "apt | ensure previous repository for Google Chrome is absent, as Google removed the x86 distribution"
  apt_repository: 
    repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main'
    state: "absent"

- name: "apt | ensure Google chrome repo present, using a workaround for missing x86 distribution"
  copy:
    content: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
    dest: "/etc/apt/sources.list.d/google-chrome.list"
  register: google_repo

- name: "apt | update cache if the Google Chrome repo has been changed"
  apt: 
    update_cache: "yes"
  when: google_repo.changed
  
- name: "apt | ensure Google chrome present"
  apt: 
    name: "google-chrome-stable"
    state: "present"
    update_cache: "yes"
    cache_valid_time: "3600" # only update cache if it hasn't been updated in 1 hour
  ignore_errors: '{{ ansible_check_mode }}' # ignoring in --check, this will fail due to pre-reqs

...
